show_keybinds = false

[applications]
ignore = [
  "Avahi SSH Server Browser",
  "Avahi VNC Server Browser",
  "Avahi Zeroconf Browser",
  "Bluetooth Manager",
  "Qt V4L2 test Utility",
  "Qt V4L2 video capture utility",
  "uuctl",
  "waypaper",
  "xgps",
  "xgpsspeed"
]
